// File generated by FlutterFire CLI.

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.

///

/// Example:

/// ```dart

/// import 'firebase_options.dart';

/// // ...

/// await Firebase.initializeApp(

///   options: DefaultFirebaseOptions.currentPlatform,

/// );

/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {

      return web;

    }

    switch (defaultTargetPlatform) {

      case TargetPlatform.android:

        return android;

      case TargetPlatform.iOS:

        throw UnsupportedError(

          'DefaultFirebaseOptions have not been configured for ios - '

          'you can reconfigure this by running the FlutterFire CLI again.',

        );

      case TargetPlatform.macOS:

        throw UnsupportedError(

          'DefaultFirebaseOptions have not been configured for macos - '

          'you can reconfigure this by running the FlutterFire CLI again.',

        );

      case TargetPlatform.windows:

        throw UnsupportedError(

          'DefaultFirebaseOptions have not been configured for windows - '

          'you can reconfigure this by running the FlutterFire CLI again.',

        );

      case TargetPlatform.linux:

        throw UnsupportedError(

          'DefaultFirebaseOptions have not been configured for linux - '

          'you can reconfigure this by running the FlutterFire CLI again.',

        );

      default:

        throw UnsupportedError(

          'DefaultFirebaseOptions are not supported for this platform.',

        );

    }

  }


  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyBw00xQwzUlYIgSDsPeWcA44Mwi3AgewoU',

    appId: '1:136012598953:web:00b7366e76320c7377a3b8',

    messagingSenderId: '136012598953',

    projectId: 'canteenpreorder-e7ea8',

    authDomain: 'canteenpreorder-e7ea8.firebaseapp.com',

    databaseURL: 'https://canteenpreorder-e7ea8-default-rtdb.firebaseio.com',

    storageBucket: 'canteenpreorder-e7ea8.appspot.com',

    measurementId: 'G-NB8ZFCE9L6',

  );

  // For Firebase JS SDK v7.20.0 and later, measurementId is optional


  static const FirebaseOptions android = FirebaseOptions(

    apiKey: 'AIzaSyBAwULbIq-gsxQMWG7Do5XJacDQUOZpj8E',

    appId: '1:136012598953:android:cf7ea5b3d0014bb377a3b8',

    messagingSenderId: '136012598953',

    projectId: 'canteenpreorder-e7ea8',

    databaseURL: 'https://canteenpreorder-e7ea8-default-rtdb.firebaseio.com',

    storageBucket: 'canteenpreorder-e7ea8.appspot.com',

  );

}

